# Generated by Django 4.1 on 2023-12-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('task1', models.CharField(max_length=256)),
                ('task2', models.CharField(max_length=256)),
                ('task3', models.CharField(max_length=256)),
                ('task4', models.CharField(max_length=256)),
                ('task5', models.CharField(max_length=256)),
                ('task6', models.CharField(max_length=256)),
                ('task7', models.CharField(max_length=256)),
                ('task8', models.CharField(max_length=256)),
                ('task9', models.CharField(max_length=256)),
                ('task10', models.CharField(max_length=256)),
                ('task11', models.CharField(max_length=256)),
                ('task12', models.CharField(max_length=256)),
                ('task13', models.CharField(max_length=256)),
                ('task14', models.CharField(max_length=256)),
                ('task15', models.CharField(max_length=256)),
                ('task16', models.CharField(max_length=256)),
                ('task17', models.CharField(max_length=256)),
                ('task18', models.CharField(max_length=256)),
                ('task19', models.CharField(max_length=256)),
                ('task20', models.CharField(max_length=256)),
            ],
        ),
    ]
