# Generated by Django 4.1 on 2023-12-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revrec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revrecmodel',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
